# Generated by Django 4.0.4 on 2022-04-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to='thumbnail/'),
        ),
    ]
